### PR TITLE
fix: dont trigger request failed for aborted requests

### PR DESCRIPTION
**Pull request by AmirthavalliG**
For intentional aborted requests dont trigger fireRequestFailed/fireRequestCompleted Event
https://github.com/SAP/openui5/blob/master/src/sap.ui.core/src/sap/ui/model/odata/ODataModel.js#L869

### CODE REVIEW

**Comment by flovogt** [comment]
Screen Shot 2020-10-14 at 14 27 55
Screen Shot 2020-10-14 at 14 31 05

@AmirthavalliG Could you investigate in this topic? When we have the `canceled` or `aborted` value?
see also https://stackoverflow.com/questions/43523935/jqxhr-statustext-abort-vs-canceled-when-aborting-the-xhr

**Comment by flovogt** [comment]
Screen Shot 2020-10-14 at 14 27 55

Here you can remove the check because we do not fire the event anymore

**Comment by AmirthavalliG** [comment]
> Screen Shot 2020-10-14 at 14 27 55
> 
> Here you can remove the check because we do not fire the event anymore

@flovogt : Done

**Comment by AmirthavalliG** [comment]
> Screen Shot 2020-10-14 at 14 31 05
> 
> @AmirthavalliG Could you investigate in this topic? When we have the `canceled` or `aborted` value?
> see also https://stackoverflow.com/questions/43523935/jqxhr-statustext-abort-vs-canceled-when-aborting-the-xhr

@flovogt : According to this https://github.com/jquery/jquery/blob/master/test/unit/ajax.js#L791. When we trigger abort in beforeSend it gives the status as `canceled` which I believe will be this scenario https://github.com/SAP/openui5-fhir/blob/master/src/sap/fhir/model/r4/lib/FHIRRequestor.js#L253. But for other scenarios if the request is sent and aborted it will give 'abort' https://github.com/jquery/jquery/blob/master/test/unit/ajax.js#L194..this https://github.com/SAP/openui5-fhir/blob/master/src/sap/fhir/model/r4/lib/FHIRRequestor.js#L112 will cause 'abort'.

**Comment by AmirthavalliG** [comment]
@flovogt : Can you review the code. If it's okay we can get a fix released today.

**Comment by flovogt** [comment]
@AmirthavalliG thanks for clarification.

Would it make sense to extend the method `isAborted` also with condition `=== "abort`? With that also no requestcomplete event will be fired. Which makes sense IMHO.

So we can replace https://github.com/SAP/openui5-fhir/blob/master/src/sap/fhir/model/r4/lib/FHIRRequestor.js#L311 with the newly introduced method.

**Comment by AmirthavalliG** [comment]
> @AmirthavalliG thanks for clarification.
> 
> Would it make sense to extend the method `isAborted` also with condition `=== "canceled`? With that also no requestcomplete event will be fired. Which makes sense IMHO.
> 
> So we can replace https://github.com/SAP/openui5-fhir/blob/master/src/sap/fhir/model/r4/lib/FHIRRequestor.js#L311 with the newly introduced method.

Yeah makes sense.Will adapt it. Thanks for the suggestion :)

**Comment by AmirthavalliG** [comment]
> @AmirthavalliG thanks for clarification.
> 
> Would it make sense to extend the method `isAborted` also with condition `=== "canceled`? With that also no requestcomplete event will be fired. Which makes sense IMHO.
> 
> So we can replace https://github.com/SAP/openui5-fhir/blob/master/src/sap/fhir/model/r4/lib/FHIRRequestor.js#L311 with the newly introduced method.

done.

**Comment by flovogt** [comment]
I would recommend to make the `isAborted` method `protected` instead of `public`. The application developer does not need the function. No event will be fired by aborting the request, so application developer won't get a `true` value in their code.

**Review by flovogt — APPROVED** [review]
LGTM 🥇

**Comment by AmirthavalliG** [comment]
> I would recommend to make the `isAborted` method `protected` instead of `public`. The application developer does not need the function. No event will be fired by aborting the request, so application developer won't get a `true` value in their code.

Done

**Pull request merged**
