### PR TITLE
fix: token fetching

### PR DESCRIPTION
**Pull request by cuhland**
Use the correct response in the callback handle.
jqXHR is undefined.

### CODE REVIEW

**Comment by KishoreKumarVivekanandan** [comment]
@cuhland - jqXHR is part of the standard callback response, we wouldn't recommend the usage of internal variable like '_jqRequest'. Can you explain more in detail about how did you come across the issue and the sample/test application to reproduce it.

**Comment by cuhland** [comment]
Hi @KishoreKumarVivekanandan 
Thanks for the reply. Let's discuss then another possibility. 
[Here](https://github.com/cuhland/openui5-fhir-sample-app/tree/cuh/demo-fixTokenFetch) is the open-ui5-fhir-sample-app with the bug.

**Comment by cuhland** [comment]
Any updates?

**Comment by cuhland** [comment]
@KishoreKumarVivekanandan Do you need more information?

**Comment by KishoreKumarVivekanandan** [comment]
Hi @cuhland Sorry that I missed the previous comment. Thanks for tagging now. 
Yes, I have looked at it and I couldn't reproduce this issue. As we already suggested we wouldnt recommend usage of internal variables, hence if you could have a better way of handling it, you could continue your contribution via this PR. 

Otherwise if its Feature request or Bug report, The communication in this PR is not an efficient way of handling the same. I would suggest you to create an issue with the Feature request or Bug report with all the relevant details to reproduce it step by step so we can take it forward based on the priority. Once the feature or bug fix is available as part of the new release you will be notified on the same.

**Comment by flovogt** [comment]
Hi @cuhland, sorry for this long ongoing task. We've checked your issue and we'll provide a fix for that.

**Comment by flovogt** [comment]
Hi @cuhland,
I've enhanced some tests and fixed the issue with https://github.com/SAP/openui5-fhir/pull/108/.

**Comment by flovogt** [comment]
Hi @cuhland ,
this fix is implemented with release [2.0.3](https://github.com/SAP/openui5-fhir/releases/tag/v2.0.3).
Thanks a lot for opening this pull request.
Best Regards,
Florian

**Pull request closed without merging**
